<?php
bolt_decrypt( __FILE__ , '5uiFj1'); return 0;
##!!!##Af4B/mJVYVlnZFVXWRQ1ZGRQQWNYWWBnLwH+Af5pZ1kUPWBgaWFdYlVoWVA4VWhVVlVnWVA5YGNlaVliaFA6VVdoY2ZdWWdQPFVnOlVXaGNmbS8B/mlnWRQ9YGBpYV1iVWhZUDhVaFVWVWdZUDlgY2VpWWJoUEFjWFlgLwH+Af5XYFVnZxRBXWxdYmc9YlpjFFlsaFliWGcUQWNYWWAB/m8B/hQUFBRpZ1kUPFVnOlVXaGNmbS8B/nEB/g==